language: java
jdk: oraclejdk14

sudo: required

services:
  - postgresql
  - docker

before_install:
  - psql -c 'create user csld with password '"'"'csld'"'"';' -U postgres
  - psql -c 'create database csld_dev with owner csld;' -U postgres
  - sudo apt-get -y install awscli
  - rm ${TRAVIS_BUILD_DIR}/src/main/resources/application.properties
  - aws s3 cp ${AWS_DIRECTORY}application.properties ${TRAVIS_BUILD_DIR}/src/main/resources/application.properties --region eu-central-1
  - rm ${TRAVIS_BUILD_DIR}/Procfile
  - aws s3 cp ${AWS_DIRECTORY}Procfile ${TRAVIS_BUILD_DIR}/Procfile --region eu-central-1

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install heroku:deploy-war -B -P integration

branches:
  only:
    - master
    - dev
    - /^integration.*$/

addons:
  sonarcloud:
    organization: "csld"
    token:
      secure: WYfCah03KZg6K/AzzJqAQQn8y6jCsK/MxZ4Fezlxx8YJ6Gk2ofQw/awfP4eGqysoPZgS3fLErExZbKAC00eDTjWhNcjSJEuyoCX6rzzwBnQn3fiVaAdNw0/WrMHV2c4RXWt6ecRFp7OxSFcRzLMRkJ0txYUrbj3cbeoIpsxnNwQ=
