language: java
jdk: oraclejdk12

sudo: required

services:
  - postgresql
  - docker

before_install:
  - psql -c 'create user csld with password '"'"'csld'"'"';' -U postgres
  - psql -c 'create database csld_dev with owner csld;' -U postgres
  - sudo apt-get -y install awscli
  - ls ${TRAVIS_BUILD_DIR}/CSLD/src/main/resources/application.properties
  - rm ${TRAVIS_BUILD_DIR}/CSLD/src/main/resources/application.properties
  - aws cp ${CONFIG_FILE_AWS} ${TRAVIS_BUILD_DIR}/CSLD/src/main/resources/application.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=CSLD_CSLD heroku:deploy-war -B -P integration

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: "csld"
    token:
      secure: WYfCah03KZg6K/AzzJqAQQn8y6jCsK/MxZ4Fezlxx8YJ6Gk2ofQw/awfP4eGqysoPZgS3fLErExZbKAC00eDTjWhNcjSJEuyoCX6rzzwBnQn3fiVaAdNw0/WrMHV2c4RXWt6ecRFp7OxSFcRzLMRkJ0txYUrbj3cbeoIpsxnNwQ=