language: java
jdk: oraclejdk12

sudo: required

services:
  - postgresql
  - docker

before_install:
  - psql -c 'create user csld with password '"'"'csld'"'"';' -U postgres
  - psql -c 'create database csld_dev with owner csld;' -U postgres
  - sudo apt-get -y install awscli

script:
  - mvn clean install -B

after_success:
  - docker build -t jbalhar/csld .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master