CREATE TABLE csld_user (
  id INT NOT NULL UNIQUE,
  user_name VARCHAR(100) NOT NULL,
  password VARCHAR(100),
  role_id INT,

  FOREIGN KEY (id) REFERENCES person(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (role_id) REFERENCES role(id) ON UPDATE CASCADE ON DELETE RESTRICT,

  PRIMARY KEY(id)
);